In [45]:
from pyprojroot import here
import pandas as pd


path = here() / 'data' / 'raw' / 'carbon_2020-01-01_2025-12-31.parquet'

df = pd.read_parquet(path)

sample = df.head()

sample.to_parquet(here() / 'data' / 'samples' / 'carbon_sample.parquet')

In [3]:
from pyprojroot import here
import pandas as pd


print(pd.__version__)
print(type(df["index"].iloc[0]))

3.0.3
<class 'str'>

In [10]:
df

,from,to,forecast,actual,index
0,2019-12-31 23:30:00+00:00,2020-01-01 00:00:00+00:00,183.0,180.0,moderate
1,2020-01-01 00:00:00+00:00,2020-01-01 00:30:00+00:00,178.0,182.0,moderate
2,2020-01-01 00:30:00+00:00,2020-01-01 01:00:00+00:00,176.0,181.0,moderate
3,2020-01-01 01:00:00+00:00,2020-01-01 01:30:00+00:00,185.0,176.0,moderate
4,2020-01-01 01:30:00+00:00,2020-01-01 02:00:00+00:00,181.0,175.0,moderate
...,...,...,...,...,...
104985,2025-12-30 21:30:00+00:00,2025-12-30 22:00:00+00:00,192.0,174.0,moderate
104986,2025-12-30 22:00:00+00:00,2025-12-30 22:30:00+00:00,191.0,159.0,moderate
104987,2025-12-30 22:30:00+00:00,2025-12-30 23:00:00+00:00,173.0,138.0,moderate
104988,2025-12-30 23:00:00+00:00,2025-12-30 23:30:00+00:00,175.0,122.0,moderate
104989,2025-12-30 23:30:00+00:00,2025-12-31 00:00:00+00:00,148.0,121.0,moderate

In [63]:
df.sort_values('column', ascending=False)

,from,to,forecast,actual,index,column
4485,2020-04-03 10:00:00+00:00,2020-04-03 10:30:00+00:00,12.0,252.0,high,240.0
73758,2024-03-19 16:30:00+00:00,2024-03-19 17:00:00+00:00,33.0,239.0,high,206.0
52432,2022-12-29 12:00:00+00:00,2022-12-29 12:30:00+00:00,245.0,45.0,low,200.0
77440,2024-06-04 09:30:00+00:00,2024-06-04 10:00:00+00:00,244.0,50.0,low,194.0
60107,2023-06-07 09:30:00+00:00,2023-06-07 10:00:00+00:00,185.0,0.0,very low,185.0
...,...,...,...,...,...,...
98184,2025-08-11 05:00:00+00:00,2025-08-11 05:30:00+00:00,NaN,152.0,moderate,NaN
98185,2025-08-11 05:30:00+00:00,2025-08-11 06:00:00+00:00,NaN,148.0,moderate,NaN
98186,2025-08-11 06:00:00+00:00,2025-08-11 06:30:00+00:00,NaN,147.0,moderate,NaN
98187,2025-08-11 06:30:00+00:00,2025-08-11 07:00:00+00:00,NaN,150.0,moderate,NaN
98188,2025-08-11 07:00:00+00:00,2025-08-11 07:30:00+00:00,NaN,146.0,moderate,NaN

In [58]:
import numpy as np

df.iloc[np.abs(df['forecast'] - df['actual']).idxmax()]['from']

Timestamp('2020-04-03 10:00:00+0000', tz='UTC')

In [4]:
print(int("8734.0"))

ValueError: invalid literal for int() with base 10: '8734.0'

In [39]:
type(df.assign(error=(df["forecast"] - df["actual"]).abs()).groupby("index").filter(lambda g: len(g) >= 100).groupby("index")["error"].mean().idxmin())

str

In [17]:
row = df[df["from"] == "2025-01-15 13:30:00"]   # ← this line ASSIGNS to a variable
print(row["forecast"].iloc[0])

222.0

In [44]:
import math
a="the answer is 222.0"
a.strip()

try:
    if math.isclose(22, float(a)):
        print('b')
except ValueError as e:
    print('try again')

try again

In [66]:
from mlx_lm import load, generate
model, tokenizer = load("Qwen/Qwen3-1.7B")

msgs = [{"role": "system", "content": "You are helpful."},
        {"role": "user", "content": "Create a neural network. /no_think"}]

prompt = tokenizer.apply_chat_template(msgs, add_generation_prompt=True, tokenize=False)

out = generate(model, tokenizer, prompt=prompt, max_tokens=512, verbose=True)
print(prompt)
split1 = out.split("```python")[1]

final_split = split1.split("```")[0]

print(final_split)

Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 112347.43it/s]

==========
<think>

</think>

Creating a neural network is a great way to understand how machine learning models work. Below is a simple example of a **feedforward neural network** using **Python** and **TensorFlow/Keras**, which is a popular deep learning library.

---

### ✅ Simple Neural Network Example (Using TensorFlow/Keras)

This example creates a simple **multi-layer perceptron (MLP)** with one hidden layer and trains it on the **MNIST dataset** (handwritten digits).

---

### 📦 Requirements

You need to have Python and TensorFlow installed. You can install TensorFlow using:

```bash
pip install tensorflow
```

---

### 🧠 Code: Simple Neural Network

```python
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# Load and preprocess data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize pixel values to [0, 1]
x_train = x_train / 255.0
x_test = x_test / 255.0

# Flatten the images (convert 28x28 to 784)
x_train = x_train.reshape((x_train.shape[0], 784))
x_test = x_test.reshape((x_test.shape[0], 784))

# Create the model
model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5)

# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_acc:.4f}")
```

---

### 📈 Output (Example)

```
Epoch 5/5
150000/150000 [==============================] - 1s 1ms per epoch
Test accuracy: 0.9865
```

---

### 🧪 Explanation

- **Input Layer**: 784 (28x28 pixels)
- **Hidden Layer**: 128 neurons with ReLU activation
- **Output Layer**: 10 neurons with softmax activation (for multi-class
==========
Prompt: 26 tokens, 7.008 tokens-per-sec
Generation: 512 tokens, 36.205 tokens-per-sec
Peak memory: 6.882 GB
<|im_start|>system
You are helpful.<|im_end|>
<|im_start|>user
Create a neural network. /no_think<|im_end|>
<|im_start|>assistant


import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# Load and preprocess data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize pixel values to [0, 1]
x_train = x_train / 255.0
x_test = x_test / 255.0

# Flatten the images (convert 28x28 to 784)
x_train = x_train.reshape((x_train.shape[0], 784))
x_test = x_test.reshape((x_test.shape[0], 784))

# Create the model
model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5)

# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_acc:.4f}")

In [130]:
from analyst_agent.agent import Agent
agent = Agent("Qwen/Qwen3-1.7B")
out = agent.generate("What is the max forecast carbon intensity, I want to see it on a pretty graph?", no_think=True, max_tokens=999999)
print(repr(out))

Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 152828.89it/s]

==========
<think>

</think>

```python
import pandas as pd
import matplotlib.pyplot as plt

# Read the data
df = pd.read_parquet("carbon_2020-01-01_2025-12-31.parquet")

# Calculate the maximum forecast carbon intensity
max_forecast = df["forecast"].max()

# Plot the forecast carbon intensity
plt.figure(figsize=(10, 6))
df.plot(x="from", y="forecast", kind="line")
plt.title("Forecast Carbon Intensity Over Time")
plt.xlabel("Time")
plt.ylabel("Carbon Intensity")
plt.grid(True)
plt.show()

print(max_forecast)
```
==========
Prompt: 515 tokens, 17.147 tokens-per-sec
Generation: 141 tokens, 35.598 tokens-per-sec
Peak memory: 10.323 GB
'<think>\n\n</think>\n\n```python\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\n# Read the data\ndf = pd.read_parquet("carbon_2020-01-01_2025-12-31.parquet")\n\n# Calculate the maximum forecast carbon intensity\nmax_forecast = df["forecast"].max()\n\n# Plot the forecast carbon intensity\nplt.figure(figsize=(10, 6))\ndf.plot(x="from", y="forecast", kind="line")\nplt.title("Forecast Carbon Intensity Over Time")\nplt.xlabel("Time")\nplt.ylabel("Carbon Intensity")\nplt.grid(True)\nplt.show()\n\nprint(max_forecast)\n```'

In [129]:
out
import re
match = re.search("```[a-z]*\s*(.*?)```", out, re.DOTALL)


match#.group(1).strip()

In [93]:
import re

match = re.search("```[a-z]*\s*(.*?)```", out, re.DOTALL)


match.group(1)

AttributeError: 'NoneType' object has no attribute 'group'

In [74]:
import re

test = re.split(r'(import)', out)
og = "".join(test[1:])
print(og)

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# Load and preprocess data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize pixel values to [0, 1]
x_train = x_train / 255.0
x_test = x_test / 255.0

# Flatten the images (convert 28x28 to 784)
x_train = x_train.reshape((x_train.shape[0], 784))
x_test = x_test.reshape((x_test.shape[0], 784))

# Create the model
model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5)

# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_acc:.4f}")
```

---

### 📈 Output (Example)

```
Epoch 5/5
150000/150000 [==============================] - 1s 1ms per epoch
Test accuracy: 0.9865
```

---

### 🧪 Explanation

- **Input Layer**: 784 (28x28 pixels)
- **Hidden Layer**: 128 neurons with ReLU activation
- **Output Layer**: 10 neurons with softmax activation (for multi-class

In [ ]:
split1 = out.split("```python")[1]

final_split = split1.split("```")[0]

import pandas as pd

# Example DataFrame
data = {
    'index': ['low', 'medium', 'high', 'high'],
    'actual': [10, 20, 30, 40]
}

df = pd.DataFrame(data)

# Compute the mean of 'actual' where 'index' is 'high'
mean_actual = df[df['index'] == 'high']['actual'].mean()

print(mean_actual)
```

### Output:
```
35.0
```

### Explanation:
- `df[df['index'] == 'high']` filters the DataFrame to include only rows where `'index'` is `'high'`.
- `['actual'].mean()` computes the mean of the `'actual'` column for those filtered rows.

Let me know if you want to handle missing values or other edge cases!

In [128]:
from typing import Optional
def addTwoNumbers(l1: Optional[list] = None, l2: Optional[list] = None) -> Optional[list]:

    value = 0
    if l1 is not None:
        l1_word = ''
        i = -1
        while i > -(len(l1)+1):
            l1_word = f"{l1_word}{l1[i]}" 
            i -= 1

        value += int(l1_word)
    
    if l2 is not None:
        l2_word = ''
        i = -1
        while i > -(len(l2)+1):
            l2_word = f"{l2_word}{l2[i]}" 
            i -= 1
        value += int(l2_word)
    
    
    value_word = str(value)

    value_list = []
    i = -1
    while i > -(len(value_word) + 1):
        value_list.append(int(value_word[i]))
        i -= 1

    return(value_list)



# l1 = [2,4,3], l2= [5,6,4]
# 342 + 465 = 807

a = addTwoNumbers(l1=[0],l2=[0])
a

[0]

In [6]:
test = {1: ['a', 'b', 'a'],
        2: ['b', 'c']}
count=0

for i in range(1, 3):
    print(test[i])
    for value in test[i]:
        match value:
            case 'b':
                count += 1


print(count)

['a', 'b', 'a']
['b', 'c']
2

In [13]:
test=[2,3,4]

sum(test)/len(test)

3.0

In [4]:
from analyst_agent.core import get_configs
import pandas as pd


agent = Agent("Qwen/Qwen3-1.7B") 
df = pd.read_parquet(get_configs()['carbon_data'])

df[(df["from"].dt.year == 2025) &(df["from"].dt.month == 1)]["forecast"].mean()

INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3-1.7B/revision/main "HTTP/1.1 200 OK"
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 19836.44it/s]

np.float64(168.45690834473325)

In [1]:
from mlx_lm.tokenizer_utils import TokenizerWrapper
from analyst_agent.agent import Agent
from analyst_agent.tools_schema import TOOLS
from analyst_agent.tasks import task1 as task
from analyst_agent.orchestrate import solve_task
from analyst_agent.core import get_configs
import pandas as pd


agent = Agent("Qwen/Qwen3-1.7B") 
df = pd.read_parquet(get_configs()['carbon_data'])


for _ in range(8):
    o = solve_task(agent, task, df, temp=0.7)
    print(type(o).__name__, '::', repr(o.raw[:200]))
    print('---')

/Users/luiscanteiro/miniforge3/envs/flywheel/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3-1.7B/revision/main "HTTP/1.1 200 OK"
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 99078.05it/s]
INFO:analyst_agent.agent:generate temp=0.7
INFO:analyst_agent.agent:generate temp=0.7
INFO:analyst_agent.agent:generate temp=0.7
INFO:analyst_agent.orchestrate:Script did not execute, model attempt will be assigned to ExecutionFail...
INFO:analyst_agent.agent:generate temp=0.7

ExecutionFail :: '<think>\n\n</think>\n\n<tool_call>\n{"name": "check_code", "arguments": {"code": "import pandas as pd\\n\\ndf = pd.read_parquet(\'carbon_2020-01-01_2025-12-31.parquet\')\\n\\n# Convert \'from\' and \'to\' columns to'
---

INFO:analyst_agent.agent:generate temp=0.7

ExtractionFail :: '<think>\n\n</think>\n\n<tool_call>\n{"name": "import", "arguments": {"code": "import pandas as pd"}}\n</tool_call>'
---

INFO:analyst_agent.agent:generate temp=0.7

ExtractionFail :: '<think>\n\n</think>\n\n<tool_call>\n{"name": "import", "arguments": {"code": "import pandas as pd"}}\n</tool_call>'
---

INFO:analyst_agent.agent:generate temp=0.7

ExtractionFail :: '<think>\n\n</think>\n\n<tool_call>\n{"name": "import", "arguments": {"code": "import pandas as pd"}}\n</tool_call>'
---

INFO:analyst_agent.agent:generate temp=0.7

ExtractionFail :: '<think>\n\n</think>\n\n<tool_call>\n{"name": "import", "arguments": {"code": "import pandas as pd"}}\n</tool_call>'
---

INFO:analyst_agent.agent:generate temp=0.7

ExtractionFail :: '<think>\n\n</think>\n\n<tool_call>\n{"name": "import pandas as pd", "arguments": {"code": "import pandas as pd\\n\\n# Read the data file\\nfile_path = \'carbon_2020-01-01_2025-12-31.parquet\'\\n\\ndf = pd.read_pa'
---

INFO:analyst_agent.agent:generate temp=0.7

ExtractionFail :: '<think>\n\n</think>\n\n<tool_call>\n{"name": "import", "arguments": {"code": "import pandas as pd"}}\n</tool_call>'
---

INFO:analyst_agent.agent:generate temp=0.7
INFO:analyst_agent.agent:generate temp=0.7
INFO:analyst_agent.orchestrate:Script did not execute, model attempt will be assigned to ExecutionFail...

ExecutionFail :: '<think>\n\n</think>\n\n<tool_call>\n{"name": "check_code", "arguments": {"code": "import pandas as pd\\n\\ndf = pd.read_parquet(\'carbon_2020-01-01_2025-12-31.parquet\')\\n\\ndef get_forecast(start_time):\\n    r'
---

In [2]:
# what the bare probe sent:
p_probe = agent.tokenizer.apply_chat_template(
    agent._build_messages(task.question, no_think=True),
    add_generation_prompt=True, tokenize=False, tools=TOOLS)

# what solve_task sends turn 1 (should be the same):
msgs = agent._build_messages(task.question, no_think=True)
p_solve = agent.tokenizer.apply_chat_template(
    msgs, add_generation_prompt=True, tokenize=False, tools=TOOLS)

print(p_probe == p_solve)

True

In [ ]:
import json

out = raw.split('<tool_call>')[1].strip().split('</tool_call>')[0].strip()

json.loads(out)

{'name': 'check_code',
 'arguments': {'code': "import pandas as pd\n\ndf = pd.read_parquet('carbon_2020-01-01_2025-12-31.parquet')\n\n# Filter for the settlement period starting at 2025-01-15 13:30:00\ntarget_time = pd.to_datetime('2025-01-15 13:30:00')\nfiltered_df = df[df['from'] == target_time]\n\n# Extract the forecast value\nforecast_value = filtered_df['forecast'].values[0]\n\nprint(forecast_value)"}}

In [31]:
raw = agent.generate(no_think=True, question=task.question, temp=0.7)
raw

'<think>\n\n</think>\n\n```python\nimport parquetfile\n\n# Read the data file\ndf = parquetfile.ParquetFile("carbon_2020-01-01_2025-12-31.parquet")\n\n# Filter the row where \'from\' is 2025-01-15 13:30:00\nfiltered_df = df[df[\'from\'] == df[\'from\'].dt.datetime(2025, 1, 15, 13, 30)]\n\n# Extract the \'forecast\' value\nforecast_value = filtered_df[\'forecast\'].values[0]\n\nprint(forecast_value)\n```'

In [ ]:
for _ in range(8):
    raw = agent.generate(no_think=True, question=task.question, temp=0.7, tools=TOOLS)
    out = raw.split('<tool_call>')[1].strip().split('</tool_call>')[0].strip()

    json.loads(out)
    print(repr(raw))
    print('---')

In [39]:
call.split('<tool_call>')[2].strip().split('</tool_call>')[0].strip()

'{"name": "read", "arguments": {"code": "df = pd.read_parquet(\'carbon_2020-01-01_2025-12-31.parquet\')"}}'

In [ ]:
call = '<think>\n\n</think>\n\n<tool_call>\n{"name": "import", "arguments": {"code": "import pandas as pd"}}\n</tool_call>\n<tool_call>\n{"name": "read", "arguments": {"code": "df = pd.read_parquet(\'carbon_2020-01-01_2025-12-31.parquet\')"}}\n</tool_call>\n<tool_call>\n{"name": "filter", "arguments": {"code": "filtered_df = df[df[\'from\'] == pd.to_datetime(\'2025-01-15 13:30:00\')]"}}\n</tool_call>\n<tool_call>\n{"name": "select", "arguments": {"code": "result = filtered_df[\'forecast\'].iloc[0]"}}\n</tool_call>'


tool_calls = call.count('<tool_call>')

for i in range(tool_calls):

    print(f'call {i}')
    print()
    out = call.split('<tool_call>')[i+1].strip().split('</tool_call>')[0].strip()
    tool_called = json.load(out)
    print(out)
    print('-'*9)

call 0

{"name": "import", "arguments": {"code": "import pandas as pd"}}
---------
call 1

{"name": "read", "arguments": {"code": "df = pd.read_parquet('carbon_2020-01-01_2025-12-31.parquet')"}}
---------
call 2

{"name": "filter", "arguments": {"code": "filtered_df = df[df['from'] == pd.to_datetime('2025-01-15 13:30:00')]"}}
---------
call 3

{"name": "select", "arguments": {"code": "result = filtered_df['forecast'].iloc[0]"}}
---------

In [41]:
call.contains('think')

AttributeError: 'str' object has no attribute 'contains'

In [3]:
raw = agent.generate(no_think=True, question=task.question, temp=0.7, tools=TOOLS)
tool_call = raw.split('<tool_call>')[1].strip().split('</tool_call>')[0].strip()
print(repr(tool_call[250:290]))   # zoom in on the bad escape

INFO:analyst_agent.agent:generate temp=0.7

"to'] >= target_date]['forecast'].mean()\\"

In [12]:
from pyprojroot import here
import json
from dataclasses import dataclass
from analyst_agent.sft.pairs import build_pairs
from analyst_agent.agent import Output
import logging
import re

logger = logging.getLogger()

def extract_code(out: str) -> Output:
        """
        Extract executable Python code from a model response.

        The function removes any reasoning enclosed within </think>
        tags before attempting to extract code blocks. If no fenced
        code block is present but Python code appears to have been
        generated, the remaining text is treated as code.

        Args:
            out: Raw model output.

        Returns:
            Output containing both the raw response and extracted code.
        """

        # Remove reasoning section (if present)
        stage_1 = out.split('</think>')[-1].strip()

        # Only attempt extraction if executable code appears present
        if 'print(' in stage_1:

            # Look for fenced Python code blocks
            match = re.search(r"```[a-z]*\s*(.*?)```", stage_1, re.DOTALL)

            # If no fenced block exists, assume the remaining text is code
            if match is None:
                code = stage_1
            else:
                code = match.group(1).strip()

        else:
            logger.info('No code extracted')
            code = None

        return Output(
            raw=out,
            code=code
        )


@dataclass
class Pair:
    prompt: list[dict[str, str]]
    target: str

with open(here() / 'reports' / 'evaluation_2026-08-12_19-30-31.json', 'r') as f:
    raw_pairs = json.load(f)


cleaned_pairs = build_pairs(raw_pairs)

for pair in cleaned_pairs:
    output = extract_code(pair.target)
    assert output.code and output.code.strip(), "empty code"
    assert '<tool_call>' not in pair.target, "target would route to tool loop"
print(f"all {len(cleaned_pairs)} round-trip clean and route to run_task")

all 147 round-trip clean and route to run_task